# Generated by Django 6.0.2 on 2026-04-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
